import { type NextPage } from "next";
import Head from "next/head";
import HomePage from "components/Index/Header/HomePage";

// TODO Maybe use Redux for everything so you dont need to refetch data on every page? 
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Shop with T3 stack and Stripe</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomePage />
      </main >
    </>
  );
};

export default Home;
