import { type NextPage } from "next";
import Head from "next/head";
import { api } from "@/utils/api";
import AuthPage from "components/Stripe/AuthPage";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from T3 Stripe App" });

  return (
    <>
      <Head>
        <title>T3 stack with Stripe</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {/* <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 "> */}
        <div className="flex flex-col items-center gap-2">
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
          <AuthPage />
        </div>
      </main >
    </>
  );
};

export default Home;
